### ISSUE TITLE
GoDonnie craches while executing more than one command 

### ISSUE THREAD

**Issue by amamory** [lsa-pucrs/donnie-assistive-robot-sw#120]
In this case, I am executing 2 commands

```
GoDonnie$ som desligado
GoDonnie$ pf 2
```
then I press ESC to execute them. GoDonnie craches while trying to run more than one command.
It works if it executes the commands individually. The log shows the error trace.

The branch was feature-vib-belt-v2, but it also happens on other branches.
use ccmake to compile Donnie for Debug.

```
(gdb) run -t
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /opt/donnie/bin/GoDonnie -t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
playerc warning   : warning : [Player v.3.0.2] connected on [localhost:6665] with sock 3

[New Thread 0x7fffedb62700 (LWP 4816)]
GoDonnie$ som desligado
GoDonnie$ pf 2
GoDonnie$ som desligado
pf 2
Tree : som desligado (pf 2)

Thread 1 "GoDonnie" received signal SIGSEGV, Segmentation fault.
0x0000000000426a1b in ExprTreeEvaluator::run (this=0x69c0e0 <Compiler>, tree=0x7ffff7ede048) at /home/osboxes/donnie_2018/donnie-assistive-robot-sw/client/godonnie/Compiler.cpp:242
242	    printf("%d", tok->type);
(gdb) where
#0  0x0000000000426a1b in ExprTreeEvaluator::run (this=0x69c0e0 <Compiler>, tree=0x7ffff7ede048) at /home/osboxes/donnie_2018/donnie-assistive-robot-sw/client/godonnie/Compiler.cpp:242
#1  0x0000000000426352 in ExprTreeEvaluator::parseGD (this=0x69c0e0 <Compiler>, textIn=0x6b2470 "som desligado\npf 2") at /home/osboxes/donnie_2018/donnie-assistive-robot-sw/client/godonnie/Compiler.cpp:209
#2  0x000000000043b91a in evalCode (count=1, key=256) at /home/osboxes/donnie_2018/donnie-assistive-robot-sw/client/godonnie/GoDonnie.cpp:327
#3  0x00007ffff7422990 in _rl_dispatch_subseq () from /lib/x86_64-linux-gnu/libreadline.so.6
#4  0x00007ffff7422e12 in readline_internal_char () from /lib/x86_64-linux-gnu/libreadline.so.6
#5  0x00007ffff7423545 in readline () from /lib/x86_64-linux-gnu/libreadline.so.6
#6  0x000000000043ad86 in main (argc=2, argv=0x7fffffffdb78) at /home/osboxes/donnie_2018/donnie-assistive-robot-sw/client/godonnie/GoDonnie.cpp:255

```

**Comment by amamory** [comment]
I tried to replicate this error in a 'clean' OS distribution of Ubuntu Mate 16.04. No errors. It suggests to be some OS issue. It needs further investigation.
